version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: $PASSWORD
    # Volumes store your data between container upgrades
    volumes:
      - '/home/martinho/pihole/etc-pihole:/etc/pihole'
      - '/home/martinho/pihole/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped