version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - passbolt
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:4.1.2-1-ce
    container_name: passbolt
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - passbolt
      - frontend
    environment:
      APP_FULL_BASE_URL: $HTTPS_URL
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: $DB_USER
      DATASOURCES_DEFAULT_PASSWORD: $DB_PASSWORD
      DATASOURCES_DEFAULT_DATABASE: $DATABASE_NAME
      EMAIL_DEFAULT_FROM: $MAIL_USER
      EMAIL_TRANSPORT_DEFAULT_HOST: "smtp.gmail.com"
      EMAIL_TRANSPORT_DEFAULT_PORT: "587"
      EMAIL_TRANSPORT_DEFAULT_TLS: "TLS"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: $MAIL_USER
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: $MAIL_PASSWORD
    labels:
      traefik.enable: "true"
      traefik.http.routers.passbolt-http.entrypoints: "web"
      traefik.http.routers.passbolt-http.rule: "Host(`$URL`)"
      traefik.http.routers.passbolt-http.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.entrypoints: "websecure"
      traefik.http.routers.passbolt-https.rule: "Host(`$URL`)"
      traefik.http.routers.passbolt-https.tls: "true"
      traefik.http.routers.passbolt-https.tls.certresolver: "letsencrypt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 8081:80
      - 8443:443

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

networks:
  monitoring:
   name: passbolt
  frontend:
   name: frontend