version: '3.9'
 
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - SERVERURL=$URL               
      - PEERS=peer  
      - PEERDNS=$DNS 
      - INTERNAL_SUBNET=$NETWORK       
      - ALLOWEDIPS=0.0.0.0/0                   
    volumes:
      - /home/martinho/wirguard/config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped